"""Generate public dashboard settings; never expose secrets or evaluate .env."""
import json
import re
from urllib.parse import urlsplit

from .config import atomic_write

PROBE_PATHS = {"n8n": "/healthz", "ollama": "/api/tags"}
PROXY_APPS = ("n8n", "penpot", "plausible", "fooocus", "ollama")


def port(settings, key):
    value = settings.get(key)
    if not value.isascii() or not value.isdecimal() or not 1 <= int(value) <= 65535:
        raise ValueError(f"{key} must be a port between 1 and 65535.")
    return int(value)


def public_url(value):
    parsed = urlsplit(value)
    if (parsed.scheme not in ("http", "https") or not parsed.hostname or
            parsed.username is not None or parsed.password is not None or
            parsed.query or parsed.fragment or any(c.isspace() for c in value)):
        raise ValueError("Dashboard URLs must be HTTP(S), without credentials, query or fragment.")
    # Accessing .port also rejects malformed and out-of-range ports.
    if parsed.port == 0:
        raise ValueError("Dashboard URLs cannot use port 0.")
    return value.rstrip("/")


def require_local_http(value, key):
    parsed = urlsplit(public_url(value))
    if parsed.scheme != "http" or parsed.hostname not in ("localhost", "127.0.0.1"):
        raise ValueError(f"{key} must be an http://localhost or http://127.0.0.1 URL.")
    return value.rstrip("/")


def local_http_upstream(value, override_path=None):
    parsed = urlsplit(public_url(value))
    if parsed.scheme != "http" or parsed.hostname not in ("localhost", "127.0.0.1"):
        return None
    path = override_path if override_path is not None else (parsed.path or "/")
    if not path.startswith("/") or ".." in path or not re.fullmatch(r"[A-Za-z0-9._/-]*", path):
        raise ValueError("Health probe path must be a simple HTTP path.")
    return parsed.port or 80, path or "/"


def configuration(settings):
    host = settings.get("DASHBOARD_HOST")
    if host not in ("localhost", "127.0.0.1"):
        raise ValueError("DASHBOARD_HOST must be localhost or 127.0.0.1; services bind locally.")
    apps = {}
    for name, key in (("dashboard", "DASHBOARD_PORT"), ("n8n", "N8N_PORT"),
                      ("penpot", "PENPOT_PORT"), ("fooocus", "FOOOCUS_PORT")):
        apps[name] = {"url": f"http://{host}:{port(settings, key)}",
                      "optional": name != "dashboard"}
    apps["n8n"]["healthUrl"] = apps["n8n"]["url"] + "/healthz"
    apps["plausible"] = {"url": public_url(settings.get("PLAUSIBLE_BASE_URL")), "optional": True}
    apps["ollama"] = {"url": require_local_http(settings.get("OLLAMA_URL"), "OLLAMA_URL"), "optional": False}
    apps["ollama"]["healthUrl"] = apps["ollama"]["url"] + "/api/tags"
    return {"apps": apps, "models": public_models(settings)}


def attach_same_origin_health(config):
    """Point browser checks at the dashboard proxy so CORS cannot hide localhost status."""
    origin = config["apps"]["dashboard"]["url"]
    for name in PROXY_APPS:
        app = config["apps"].get(name)
        if not app:
            continue
        upstream = local_http_upstream(app["url"], PROBE_PATHS.get(name))
        if upstream is None:
            continue
        app["healthUrl"] = f"{origin}/health/{name}"
        app["healthKind"] = name
    return config


def status_proxy_conf(config):
    lines = ["# Generated by pt dashboard. GET-only localhost health probes.", ""]
    for name in PROXY_APPS:
        app = config["apps"].get(name)
        if not app:
            continue
        upstream = local_http_upstream(app["url"], PROBE_PATHS.get(name))
        if upstream is None:
            continue
        port_number, path = upstream
        lines += [
            f"location = /health/{name} {{",
            f"    proxy_pass http://host.docker.internal:{port_number}{path};",
            "    proxy_http_version 1.1;",
            "    proxy_connect_timeout 2s;",
            "    proxy_read_timeout 3s;",
            "    proxy_set_header Cookie \"\";",
            "    proxy_set_header Authorization \"\";",
            "    proxy_hide_header Set-Cookie;",
            "    proxy_hide_header Authorization;",
            "    limit_except GET HEAD { deny all; }",
            "}",
            "",
        ]
    return "\n".join(lines)


def public_models(settings):
    def token(key):
        value = settings.get(key)
        if (not value or ".." in value or value.startswith("/") or
                not re.fullmatch(r"[A-Za-z0-9._:/-]{1,80}", value)):
            raise ValueError(f"{key} is not a public model identifier.")
        return value

    language = (settings.get("WHISPER_LANGUAGE") or "").strip().lower()
    if not language or language in ("auto", "detect"):
        language = "auto"
    elif not re.fullmatch(r"[a-z]{2}(-[a-z]{2})?", language):
        raise ValueError("WHISPER_LANGUAGE must be empty (auto) or a language code such as nl.")
    return {"ollama": token("OLLAMA_MODEL"), "whisper": token("WHISPER_MODEL"), "whisperLanguage": language}


def render(settings):
    config = attach_same_origin_health(configuration(settings))
    # Public, allowlisted values only; nginx must be able to read these files.
    atomic_write(settings.root / "dashboard/config.js",
                 "window.DASHBOARD_CONFIG = " + json.dumps(config, ensure_ascii=True) + ";\n",
                 mode=0o644)
    atomic_write(settings.root / "dashboard/status-proxy.conf", status_proxy_conf(config), mode=0o644)
    return config["apps"]["dashboard"]["url"]
