#!/usr/bin/env bash
# Render dashboard/config.js from .env
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
OUT="${ROOT}/dashboard/config.js"

if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1091
  set -a
  source "${ENV_FILE}"
  set +a
fi

HOST="${DASHBOARD_HOST:-localhost}"
N8N_PORT="${N8N_PORT:-5678}"
PENPOT_PORT="${PENPOT_PORT:-9001}"
PLAUSIBLE_PORT="${PLAUSIBLE_HTTP_PORT:-8000}"
DASHBOARD_PORT="${DASHBOARD_PORT:-8080}"
OLLAMA_PORT="${OLLAMA_PORT:-11434}"
FOOOCUS_PORT="${FOOOCUS_PORT:-7865}"

cat > "${OUT}" <<EOF
// Generated by scripts/render-dashboard-config.sh
window.DASHBOARD_CONFIG = {
  host: "${HOST}",
  apps: {
    n8n:       { port: ${N8N_PORT},       path: "", label: "n8n",       optional: false },
    penpot:    { port: ${PENPOT_PORT},    path: "", label: "Penpot",    optional: false },
    plausible: { port: ${PLAUSIBLE_PORT}, path: "", label: "Plausible", optional: true },
    ollama:    { port: ${OLLAMA_PORT},    path: "", label: "Ollama",    optional: false },
    fooocus:   { port: ${FOOOCUS_PORT},   path: "", label: "Fooocus",   optional: true },
    dashboard: { port: ${DASHBOARD_PORT}, path: "", label: "Dashboard", optional: false },
  },
};
EOF

echo "Rendered ${OUT}"
